// ============================================================
// SYSTEM KNOWLEDGE FILE — Smart Teacher Assistant
// Lesson Plan & Exam Generation System
// ============================================================
// This file is the permanent knowledge base for the AI pipeline.
// It is loaded server-side and passed into Prompt 1 (Draft Generator)
// and Prompt 2 (Pedagogical Tuner) at runtime.
// Never embed this data directly in code — always load from this file.
// ============================================================

const promptsHelper = {
  // ============================================================
  // PEDAGOGICAL RULES
  // Extracted from the official project document sections:
  //   - القواعد التربوية المنظمة لعملية التوليد
  //   - مجالات الأهداف السلوكية
  // Used by Prompt 2 (Pedagogical Tuner) to validate and repair
  // lesson plans generated by Prompt 1.
  // These rules enforce measurable objectives, Bloom alignment,
  // activity-objective linkage, and time distribution.
  // Also used by the backend validator before saving to database.
  // ============================================================
  "pedagogical_rules": {

    // Objective must follow this exact Arabic grammatical pattern.
    // Prompt 2 uses this to rewrite any objective that does not conform.
    // Source: قاعدة الهدف السلوكي من الوثيقة الرسمية
    "objective_format": {
      "pattern": "أن + فعل سلوكي + الطالب + محتوى من المادة + شرط/معيار",
      "example": "أن يكتب الطالب أركان الصلاة من الذاكرة على السبورة بدقة"
    },

    // Used by Prompt 2 to prevent generating non-measurable objectives.
    // These verbs are explicitly forbidden by the pedagogical rules document.
    // Backend validator will reject any objective containing these verbs.
    "forbidden_verbs": ["يفهم", "يعرف", "يتعرف"],

    // Used by backend validation and Prompt 2 to check that
    // lesson timing follows pedagogical standards.
    // Source: قاعدة توزيع زمن الحصة
    // Values represent percentage of total lesson duration.
    "time_distribution": {
      "intro": 0.10,
      "presentation": 0.60,
      "activity": 0.20,
      "assessment": 0.10
    },

    // Core alignment rules enforced by Prompt 2 and backend validator.
    // Source: قاعدة التوافق بين الأهداف — مبدأ الموائمة
    // Every objective must have a corresponding activity AND assessment item.
    "alignment_rules": {
      "every_objective_has_activity": true,
      "every_objective_has_assessment_item": true,
      "no_assessment_question_outside_objective": true,
      "no_activity_without_objective": true
    },

    // Rules governing objective quality.
    // Prompt 2 checks each generated objective against these rules.
    // Note: not every lesson must include all three domains —
    // domain coverage depends on lesson content and grade level.
    "objectives_rules": {
      "must_be_measurable": true,
      "must_use_behavioral_verb": true,
      "linked_to_bloom": true,
      // Possible domains a lesson may address — not all are required in every lesson.
      "domains": ["معرفي", "وجداني", "مهاري"],
      // Soft rule: Prompt 2 should attempt domain variety but not force all three.
      "not_every_lesson_requires_all_domains": true,
      "minimum_count": 1
    },

    // Rules governing activity quality.
    // Prompt 2 uses these when selecting or repairing activity blocks.
    "activities_rules": {
      "must_be_varied": true,
      "appropriate_for_grade_level": true,
      "each_activity_linked_to_objective": true
    },

    // Rules governing assessment question quality.
    // Source: قاعدة جودة الأسئلة التقويمية
    // Prompt 2 uses question_types to select valid question formats only.
    "assessment_rules": {
      "each_objective_has_assessment_question": true,
      "question_variety_required": true,
      // Exact question types as defined in the official document.
      // Prompt 2 must only use these types — no other formats allowed.
      "question_types": ["لا أو نعم", "اختيار متعدد", "إملاء الفراغ", "سؤال مفتوح"],
      "must_match_bloom_level_of_objective": true,
      "not_all_recall": true,
      "appropriate_for_student_level": true
    },

    // Rules governing homework quality.
    // Source: قاعدة جودة الواجبات
    "homework_rules": {
      "derived_from_lesson_content": true,
      "appropriate_for_student_level": true
    },

    // Rules governing exam generation quality.
    // Source: قاعدة جودة الاختبارات
    // Exam generation is a separate pipeline that depends on previously
    // generated lesson plans stored in the local database.
    "exam_rules": {
      "questions_from_previously_prepared_lessons_only": true,
      "subject_to_specification_table": true,
      // Exact question types as defined in the official document.
      "question_types": ["لا أو نعم", "اختيار متعدد", "إملاء الفراغ", "سؤال مفتوح"],
      "marks_distributed_per_specification_table": true,
      "total_marks_not_exceeded": true,
      // Teacher inputs these values manually in the UI.
      "total_question_count_entered_by_teacher": true,
      "total_marks_entered_by_teacher": true,
      // The system auto-calculates distribution — teacher does not set it manually.
      "distribution_calculated_by_system": true
    },

    // Formulas used by the exam generation engine to calculate
    // question counts and mark distribution per topic and objective level.
    // Source: خطوات إعداد جدول المواصفات
    "specification_table_rules": {
      "topic_relative_importance": "عدد حصص الموضوع / إجمالي عدد الحصص الداخلة في الاختبار × 100",
      "objective_level_relative_importance": "عدد الأهداف من مستوى معين / إجمالي عدد الأهداف الداخلة في الاختبار × 100",
      "questions_per_topic": "الأهمية النسبية للموضوع × الأهمية النسبية للهدف × عدد الأسئلة الكلية",
      "marks_per_question": "الأهمية النسبية للموضوع × الأهمية النسبية للهدف × الدرجة النهائية"
    }
  },

  // ============================================================
  // BLOOM VERBS — GENERATION BANK
  // Extracted from: مجالات الأهداف السلوكية — المجال المعرفي
  // Renamed to bloom_verbs_generation to distinguish from the full
  // taxonomy reference. This is a curated subset optimized for
  // classroom-usable, measurable verb generation only.
  //
  // Used by Prompt 2 (Pedagogical Tuner) when:
  //   - Repairing non-measurable objectives
  //   - Suggesting better objective phrasing
  //   - Ensuring Bloom level alignment per objective
  //
  // Rules applied to this list:
  //   - Forbidden verbs (يفهم، يعرف، يتعرف) are excluded
  //   - Weak or ambiguous verbs are excluded
  //   - Only cognitive domain is included (MVP scope)
  //   - Affective and psychomotor domains are reserved for Phase 2
  // ============================================================
  "bloom_verbs_generation": {

    // Level 1 — التذكر
    // Lowest cognitive level. Used for recall-based objectives.
    "remember": [
      "يذكر", "يصف", "يسمي", "يتلو", "يستعيد",
      "يرتب", "يميز", "ينظم", "يستخرج", "يلصق", "يخطط"
    ],

    // Level 2 — الفهم
    // Used for objectives requiring interpretation or explanation.
    // Note: يفهم is excluded — it is in forbidden_verbs.
    "understand": [
      "يترجم", "يفسر", "يشرح", "يوضح", "يستدل",
      "يصنف", "يوجز", "يناقش", "يمثل", "يستعرض",
      "يعيد صياغة", "يعطي أمثلة", "يستنتج", "يعيد كتابة", "يغير", "يكمل"
    ],

    // Level 3 — التطبيق
    // Used for objectives requiring execution or use of knowledge.
    "apply": [
      "يطبق", "ينفذ", "يحل", "يستخدم", "يجرب",
      "يجري عملية", "يلاحظ", "يرسم شكلاً", "يرسم مخططاً",
      "يعلل", "يحل مسألة", "يربط", "يبرهن", "يوظف", "يبرز"
    ],

    // Level 4 — التحليل
    // Used for objectives requiring breakdown or differentiation.
    "analyze": [
      "يقارن", "يحلل", "يميز", "يفرق", "يحسب",
      "يباين", "يصنف", "يختبر", "يستنتج", "يجزئ",
      "يخمن", "يربط", "يرتب", "يبرهن"
    ],

    // Level 5 — التركيب
    // Used for objectives requiring construction or design.
    "synthesize": [
      "يركب", "ينتج", "يشتق", "يعيد بناء", "ينظم",
      "يجمع", "يقترح", "يبتكر", "يصمم", "يلخص",
      "يبني", "يؤلف", "يخترع", "يطور", "يربط بين", "يكتب"
    ],

    // Level 6 — التقويم
    // Highest cognitive level. Used for judgment and critical evaluation objectives.
    "evaluate": [
      "يقوم", "يبرر", "يدافع", "يوازن", "ينقد",
      "يقيم", "يقيس", "يختار", "يقرر", "يحكم",
      "يجادل", "يبين رأيه", "يتخذ قراراً", "يصدر حكماً", "يتبنى"
    ]
  },

  // ============================================================
  // TRADITIONAL TEACHING STRATEGIES
  // Extracted from: طرق واستراتيجيات التدريس الخاصة بالخطة التقليدية
  //
  // Strategies allowed when plan_type = "traditional".
  // Passed to Prompt 2 so the model selects only from this list
  // and cannot invent or hallucinate teaching strategies.
  //
  // Each object contains only decision-relevant fields:
  //   name           — strategy identifier shown in UI
  //   phases         — valid lesson phases this strategy applies to
  //   execution_pattern — one or two sentence operational description
  //   resources      — physical or digital tools required
  //
  // Phases must only be one or more of:
  //   intro | presentation | activity | assessment
  // This matches the system time_distribution rule exactly.
  // ============================================================
  "traditional_strategies": [
    {
      "name": "طريقة الإلقاء / المحاضرة",
      "phases": ["presentation"],
      "execution_pattern": "المعلم يعرض المحتوى مباشرة ومنظماً مع أمثلة توضيحية وأسئلة قصيرة للتأكد من الفهم",
      "resources": ["السبورة", "العروض التقديمية", "الكتاب المدرسي", "شرائح PowerPoint"]
    },
    {
      "name": "طريقة المناقشة والحوار",
      "phases": ["intro", "presentation", "assessment"],
      "execution_pattern": "المعلم يطرح أسئلة مفتوحة أو موجهة ويدير حواراً منظماً بين الطلاب مع تنظيم المشاركات وتصويب الإجابات",
      "resources": ["قائمة أسئلة معدة مسبقاً", "بطاقات أسئلة", "السبورة"]
    },
    {
      "name": "الطريقة الاستقرائية",
      "phases": ["presentation", "activity"],
      "execution_pattern": "المعلم يعرض أمثلة متعددة ثم يوجه الطلاب لاستخلاص القاعدة أو التعميم عبر التحليل والمقارنة",
      "resources": ["بطاقات أمثلة", "نصوص قصيرة", "تمارين تطبيقية"]
    },
    {
      "name": "الطريقة الاستنتاجية (القياسية)",
      "phases": ["presentation", "activity"],
      "execution_pattern": "المعلم يبدأ بعرض القاعدة أو القانون العام ثم يقدم أمثلة تطبيقية ويكلف الطلاب بحل تدريبات مشابهة",
      "resources": ["الكتاب المدرسي", "أوراق عمل", "تمارين تطبيقية"]
    },
    {
      "name": "طريقة العرض العملي (البيان العملي)",
      "phases": ["presentation", "activity"],
      "execution_pattern": "المعلم يؤدي المهارة أو التجربة أمام الطلاب مع شرح الخطوات بالتسلسل ثم يسمح بالممارسة إن أمكن",
      "resources": ["أدوات وتجهيزات مخبرية", "نماذج تعليمية", "وسائل سمعية وبصرية"]
    },
    {
      "name": "طريقة حل المشكلات",
      "phases": ["activity"],
      "execution_pattern": "المعلم يعرض مشكلة تعليمية ويساعد الطلاب على تحديدها وجمع المعلومات واقتراح الحلول واختبار الحل الأنسب",
      "resources": ["مواقف حياتية", "أوراق عمل", "تجارب", "مصادر معلومات متنوعة"]
    },
    {
      "name": "طريقة المشروع",
      "phases": ["activity"],
      "execution_pattern": "المعلم يحدد موضوع المشروع ويوزع الأدوار ويحدد مدة التنفيذ ثم يُعرض المنتج النهائي ويُقوَّم",
      "resources": ["خامات وأدوات متنوعة", "مصادر بحث", "حاسوب", "مواد تعليمية"]
    },
    {
      "name": "طريقة لعب الأدوار",
      "phases": ["activity"],
      "execution_pattern": "المعلم يحدد الموقف والأدوار ويوزع الشخصيات على الطلاب ثم يتم التمثيل وتُناقش النتائج",
      "resources": ["بطاقات أدوار", "نصوص قصيرة", "ملصقات تعريفية للشخصيات"]
    },
    {
      "name": "التعلم بالاكتشاف",
      "phases": ["activity"],
      "execution_pattern": "المعلم يطرح موقفاً استكشافياً ويوجه الطلاب بأسئلة محفزة ويقودهم للوصول إلى التعميم بأنفسهم",
      "resources": ["تجارب", "أدوات قياس", "بطاقات نشاط"]
    },
    {
      "name": "التعلم التعاوني",
      "phases": ["activity"],
      "execution_pattern": "يُقسَّم الطلاب إلى مجموعات صغيرة تُوزع الأدوار ثم يُنفَّذ النشاط ويُقوَّم الأداء الفردي والجماعي",
      "resources": ["أوراق عمل جماعية", "بطاقات أدوار", "أدوات عرض"]
    },
    {
      "name": "التعلم المبرمج",
      "phases": ["activity"],
      "execution_pattern": "المحتوى يُقدَّم في خطوات صغيرة متتابعة يستجيب فيها الطالب ويتلقى تغذية راجعة فورية قبل الانتقال للخطوة التالية",
      "resources": ["كتب مبرمجة", "برمجيات تعليمية", "منصات رقمية"]
    }
  ],

  // ============================================================
  // ACTIVE LEARNING STRATEGIES
  // Extracted from: استراتيجيات التعلم النشط
  //
  // Strategies allowed when plan_type = "active_learning".
  // Passed to Prompt 2 so the model selects only from this list
  // and cannot invent or hallucinate teaching strategies.
  //
  // Each object contains only decision-relevant fields:
  //   name           — strategy identifier shown in UI
  //   phases         — valid lesson phases this strategy applies to
  //   execution_pattern — one or two sentence operational description
  //   resources      — physical or digital tools required
  //
  // Phases must only be one or more of:
  //   intro | presentation | activity | assessment
  // This matches the system time_distribution rule exactly.
  // ============================================================
  "active_learning_strategies": [
    {
      "name": "استراتيجية القطار",
      "phases": ["activity", "assessment"],
      "execution_pattern": "تُصف الكراسي على هيئة قطار، المعلم يعرض سؤالاً، الطلاب يحلون فردياً، من يجيب صحيحاً يصعد القطار مع تعزيز من المعلم",
      "resources": ["نشيد القطار (توت توت)"]
    },
    {
      "name": "استراتيجية ابحث عن النصف الآخر",
      "phases": ["activity", "assessment"],
      "execution_pattern": "المعلم يُعد بطاقات مقسومة (سؤال وجواب)، توزع على الطلاب، كل طالب يبحث عن زميله الذي يحمل النصف المكمل، ثم تستعرض الإجابات",
      "resources": ["بطاقات مقسومة (سؤال وجواب)"]
    },
    {
      "name": "استراتيجية مكعب الأسئلة",
      "phases": ["intro", "activity"],
      "execution_pattern": "يُقسَّم الطلاب إلى مجموعات وتُحدد الأدوار، يرمي الطالب المكعب ويجيب على السؤال الذي يظهر له",
      "resources": ["مكعب يحتوي على أوجه (قارن، اكتشف، ماذا لو، صف، ما رأيك، اقترح)"]
    },
    {
      "name": "استراتيجية تيك تاك تو (X-O)",
      "phases": ["assessment"],
      "execution_pattern": "يُقسَّم الصف إلى مجموعتين، عند الإجابة الصحيحة يضع الطالب علامة فريقه، الفائز من يكمل خطاً أفقياً أو عمودياً أو قطرياً",
      "resources": ["شبكة لعب X O"]
    },
    {
      "name": "استراتيجية اكشف أوراقك",
      "phases": ["assessment"],
      "execution_pattern": "قائد المجموعة يختار بطاقة سؤال ويقرأها، الطلاب يكتبون إجاباتهم ثم يكشفونها في آنٍ واحد عند الطلب",
      "resources": ["بطاقات أسئلة"]
    },
    {
      "name": "استراتيجية ورقة الدقيقة الواحدة",
      "phases": ["intro", "presentation", "assessment"],
      "execution_pattern": "المعلم يوجه سؤالاً ويشترط الإجابة كتابياً خلال 60 ثانية، يمكن زيادة الوقت قليلاً للأسئلة الصعبة",
      "resources": ["ساعة إيقاف (مؤقت)"]
    },
    {
      "name": "استراتيجية أوجد الخطأ",
      "phases": ["activity", "assessment"],
      "execution_pattern": "المعلم يقدم فقرات تحتوي على أخطاء مقصودة ويطلب من الطلاب اكتشاف الخطأ وتصحيحه",
      "resources": ["نصوص أو بطاقات تحتوي على أخطاء وصواب"]
    },
    {
      "name": "استراتيجية أصدقاء الساعة",
      "phases": ["activity", "assessment"],
      "execution_pattern": "يوزع المعلم نموذج ساعة لكل طالب، يسجل الطالب اسم زميل عند كل ساعة، عند نداء ساعة معينة يتجه لزميله المحدد للنقاش أو الحل",
      "resources": ["نموذج ورقي للساعة بأسماء الطلاب"]
    },
    {
      "name": "استراتيجية بطاقة خروج من الصف",
      "phases": ["assessment"],
      "execution_pattern": "قبل نهاية الحصة يسأل المعلم سؤالاً، يقرأ الطالب البطاقة ويجيب عنها، الإجابة الصحيحة تسمح للطالب بمغادرة الصف",
      "resources": ["بطاقة 'يسمح للطالب بالخروج'"]
    },
    {
      "name": "استراتيجية جداول التعلم (K.W.L)",
      "phases": ["intro", "assessment"],
      "execution_pattern": "الطالب يملأ جدولاً بثلاث خانات: ماذا تعرف؟ / ماذا تريد أن تعرف؟ / ماذا تعلمت؟",
      "resources": ["جدول مقسم لثلاث خانات (K-W-L)"]
    },
    {
      "name": "استراتيجية فكر - زاوج - شارك",
      "phases": ["activity", "assessment"],
      "execution_pattern": "المعلم يطرح سؤالاً، الطالب يفكر فردياً ثم يتناقش مع زميله المجاور ثم يشاركون الإجابة مع الصف",
      "resources": ["أيقونات تعبيرية (رأس يفكر، شخصين يتحدثان، مجموعة)"]
    },
    {
      "name": "استراتيجية أعواد المثلجات",
      "phases": ["activity", "assessment"],
      "execution_pattern": "تُكتب أسماء الطلاب على أعواد في علبة، عند طرح سؤال يسحب المعلم عوداً عشوائياً ويجيب الطالب المختار ثم يُعاد العود للعلبة",
      "resources": ["أعواد خشبية مكتوب عليها أسماء الطلاب"]
    },
    {
      "name": "استراتيجية المفاهيم الكرتونية",
      "phases": ["intro", "activity", "assessment"],
      "execution_pattern": "يُجهَّز حوار كرتوني بين شخصيات حول قضية علمية تثير تساؤلات مما يدفع الطلاب للنقاش والوصول للحل الصحيح",
      "resources": ["رسومات لشخصيات مع فقاعات حوار"]
    },
    {
      "name": "استراتيجية من أنا؟",
      "phases": ["intro", "activity"],
      "execution_pattern": "تُلصق ورقة خلف ظهر الطالب تحتوي على مفهوم لا يراه، يسأل زملاءه تلميحات حتى يصل للمفهوم",
      "resources": ["بطاقات لاصقة للمفاهيم"]
    }
  ],

  // ============================================================
  // OUTPUT TEMPLATES
  // Extracted from the official document lesson plan templates.
  // These schemas define the exact JSON structure that Prompt 1
  // must produce and Prompt 2 must preserve.
  //
  // Two plan types are supported:
  //   traditional_plan_schema    — for plan_type = "traditional"
  //   active_learning_plan_schema — for plan_type = "active_learning"
  //
  // Both schemas share a unified header structure for consistency
  // in rendering and backend validation.
  // Frontend renderer reads plan_json and maps fields to UI components.
  // Do not change field names without updating the renderer.
  // ============================================================
  "output_templates": {

    // Schema for traditional lesson plans.
    // Structured as a classic matrix layout:
    // learning_outcomes | teaching_strategies | activities | learning_resources | assessment
    "traditional_plan_schema": {
      "header": {
        "date": "",
        "day": "",
        "grade": "",
        "section": "",
        "lesson_title": "",
        "unit": "",
        "duration": ""
      },
      "intro": "",
      "concepts": [],
      "learning_outcomes": [],
      "teaching_strategies": [],
      "activities": [],
      "learning_resources": [],
      "assessment": [],
      "homework": "",
      "source": ""
    },

    // Schema for active learning lesson plans.
    // Structured as a time-sequenced lesson_flow table.
    "active_learning_plan_schema": {
      "header": {
        "date": "",
        "day": "",
        "subject": "",
        "grade": "",
        "section": "",
        "lesson_title": "",
        "unit": "",
        "duration": ""
      },
      "objectives": [],
      "lesson_flow": [
        {
          "time": "",
          "content": "",
          "activity_type": "",
          "teacher_activity": "",
          "student_activity": "",
          "learning_resources": []
        }
      ],
      "homework": ""
    }
  }
};

export default promptsHelper;
